### ISSUE TITLE
Alignment Issue with the feature section

### ISSUE THREAD

**Issue by adityapandey23** [Aryainguz/picwise.co#1]
The feature section has some alignment issue. It isn't centered properly. Can you assign this issue to me so that I can start working on it!

**Comment by adityapandey23** [comment]
![image](https://github.com/user-attachments/assets/ba65d73e-6989-44ea-bb56-4d692511c251)

This is the screenshot of the issue

**Comment by Aryainguz** [comment]
go ahead on this one also upload ss on submitting pull request for this

**Comment by adityapandey23** [comment]
![image](https://github.com/user-attachments/assets/48baa580-1890-4d1d-9e85-3112ea0c5baf)

Does this looks good?
(left: modified---right: original )

**Comment by adityapandey23** [comment]
@Aryainguz Can I have a green flag?

**Comment by Aryainguz** [comment]
Yes please do a pr

**Comment by adityapandey23** [comment]
Hey @Aryainguz ,
I have created a pull request #11 
And was just curious will this be counted towards the Ggsoc-ext and hacktoberfest contribution?
Looking forward for more contributions towards this repo

**Comment by adityapandey23** [comment]
Hey @Aryainguz , It's great that this pr has been merged!! Looking forward to contribute more the repository.
Whenever you get time, can you please add the gssoc-ext and the hacktober fest label so that I can represent my contribution?
Thanks in advance!!
