### ISSUE TITLE
Drag and Drop Image Card Triggers "Select Dialog" Twice

### ISSUE THREAD

**Issue by mohit-2003** [Aryainguz/picwise.co#12]
When clicking on the "Drag and Drop Image" card, the file selection dialog opens twice every time. This bug affects the user experience by causing multiple dialog windows to appear simultaneously.

See the attached video -

https://github.com/user-attachments/assets/d08f6d7c-3151-4f5b-a865-722ff4c0ea6c

**Comment by Aryainguz** [comment]
Hey Mohit please refer to the already existing issue same as this #4

**Comment by mohit-2003** [comment]
Hi @Aryainguz, #4 is also closed, and as I can see, this issue already exists on the Pics website. Please let me know if I can work on this.
