### ISSUE TITLE
"Watch Demo" Button in Hero Section Redirects to YouTube Instead of Opening in a Dialog

### ISSUE THREAD

**Issue by mohit-2003** [Aryainguz/picwise.co#13]
Currently, when the "Watch Demo" button in the hero section is clicked, it redirects users to YouTube.com to view the demo. This external redirection affects user experience by taking them away from the website.

### Proposed Solution:
Instead of redirecting to YouTube, the demo video should be displayed in a dialog/modal within the same website. This will improve user engagement by keeping visitors on the site while viewing the demo.

This change would enhance the user experience by providing a more seamless interaction.

**Comment by Aryainguz** [comment]
That sounds better and cool approach go ahead on this, and please make sure to have responsiveness and also share screenshots/video while submitting the pr
