### ISSUE TITLE
Adding back-to-top button

### ISSUE THREAD

**Issue by SharizHussain** [Aryainguz/picwise.co#16]
There should be a back-to-top button just like below image :

![WhatsApp Image 2024-10-02 at 23 22 16](https://github.com/user-attachments/assets/8030f03d-5872-4a72-bb93-a0a0df8ed752)

You can assign me, I will add the button to improve user experiences. & add label gssoc and hacktoberfest

**Comment by sambedan1** [comment]
i contribute this in another project so  i have a great knowledge about it .please assign this to me
