### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by haseebzaki-07** [Aryainguz/picwise.co#19]
I want to add Dockerfile to the root of the project.

A Dockerfile is a text file that contains instructions for building a Docker image of the Application.
Dockerfiles are used to create container images for an application. They can be used to build multi-layer images that are automated and based on unique configurations making the development process much easier and efficient.

**Comment by Aryainguz** [comment]
hey @haseebzaki-07 it will be cool, go ahead and add it
