### ISSUE TITLE
[BUG] :  Layout Shift on Drawer Opening

### ISSUE THREAD

**Issue by Someshog** [Aryainguz/picwise.co#24]
##
##
**Steps to Reproduce:**

1) Open the application on a mobile device.
2) Trigger the drawer by clicking the 3 bars icon on top right.
3) Observe the layout shift that occurs at the bottom.

***Expected Behavior :*** The layout should remain stable, and the content should not shift when the drawer is opened.
***Actual Behavior :*** Content shifts downwards, affecting the overall layout.

***Screenshots:***

<img width="476" alt="BEFORE" src="https://github.com/user-attachments/assets/c3363731-431d-4f3c-a97b-058a1fadd176">
<img width="475" alt="AFTER" src="https://github.com/user-attachments/assets/ca07a9b9-c2c6-4c5e-9f88-d2eac9816d1d">

***Additional Notes:***
- This issue appears in both desktop and mobile views.
- Consider checking CSS properties affecting the layout (e.g., position relative or absolute).

_**Labels:** Please assign under the following labels: **`gssoc-ext`**, and **`hacktoberfest`**_

**Comment by Aryainguz** [comment]
Go ahead on this @Someshog
