### ISSUE TITLE
Dockerize Picwise

### ISSUE THREAD

**Issue by mohit-2003** [Aryainguz/picwise.co#25]
I would like to add a Dockerfile to dockerize our **Picwise** application. This will help in creating a consistent environment for development, testing, and production. Benefits include:

- Easier setup with all dependencies packaged in the container.
- Portability across different machines and cloud platforms.
- Simplified deployment process by running the app in an isolated container.

I would like to contribute as part of my GSSoC 2024 Extd and Hacktoberfest participation. Kindly let me know the process for making this contribution.

**Comment by Aryainguz** [comment]
Sure go ahead @mohit-2003

**Comment by Aryainguz** [comment]
@mohit-2003 sorry the similar issue to this has been merged recently you can contribute to some other features thanks!
