### ISSUE TITLE
[FEATURE]: Dockerize the Application

### ISSUE THREAD

**Issue by PankajKumardev** [Aryainguz/picwise.co#26]
I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .

Describe the solution you'd like
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies. 

[x ] I am contributing under GSSoC-ext
[x ] I am contributing under hacktoberfest
[x ] I follow contribution guidlines

**Comment by Aryainguz** [comment]
Hey @PankajKumardev the project already has a dockerfile, please look into adding some other features, thanks!
