### ISSUE TITLE
Menu Button Visibility on Screen Resize

### ISSUE THREAD

**Issue by Uzairkazi695** [Aryainguz/picwise.co#27]
When the menu button is clicked on mobile view, the menu items are displayed as expected. However, the menu items remain visible upon resizing the screen to a larger viewport (like a desktop).

Expected Behavior:
The menu items should automatically hide when switching from a mobile view to a larger screen.

![Screenshot 2024-10-05 195218](https://github.com/user-attachments/assets/878ffb8d-c0c1-4a06-83af-4686f953f9c9)

Labels: Please assign under the following labels: gssoc-ext, and hacktoberfest

**Comment by AdityaJ2305** [comment]
Hey, Can You assign this issue to me I would like to work on this

**Comment by Uzairkazi695** [comment]
I have already solved the issue just waiting for assigning me. and labels

**Comment by AdityaJ2305** [comment]
ok no problem
