### ISSUE TITLE
(Documentation) Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [Aryainguz/picwise.co#32]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by Aryainguz** [comment]
hey @KiranBaliga please go ahead on this

**Comment by KiranBaliga** [comment]
@Aryainguz Please review the PR and action accordingly. Thank you!
