### ISSUE TITLE
(Documentation) Add code of conduct

### ISSUE THREAD

**Issue by KiranBaliga** [Aryainguz/picwise.co#33]
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext & level1 Labels.

**Comment by KiranBaliga** [comment]
@Aryainguz Please assign to me

**Comment by Aryainguz** [comment]
go ahead on this @KiranBaliga also we aim code of conduct for this project to be unique and different than other projects you can add basic code of conduct on approaching issues and pr but please mention our rule that we don't accept non progressive issues or pr which doesn't add something important to the project, thanks!

**Comment by KiranBaliga** [comment]
@Aryainguz Please review the PR and action accordingly. Thank you!

**Comment by KiranBaliga** [comment]
@Aryainguz please review the PR. Thanks
