### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Aryainguz/picwise.co#38]
Dear Project Admin, [picwise.co](https://github.com/Aryainguz/picwise.co)
It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

gssoc-ext
level1, level2, level3
hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)
NOTE: Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by Aryainguz** [comment]
@AKSHITHA-CHILUKA thanks for getting back, i've fixed the label issues now. Do let me know if there's still some changes needed to be done, thanks!

**Comment by AKSHITHA-CHILUKA** [comment]
![image](https://github.com/user-attachments/assets/bc449f2f-18c3-46f5-a92d-10aecf648d11)
Its not gssoc its gssoc-ext please remove gssoc label and add the correct one

**Comment by AKSHITHA-CHILUKA** [comment]
also make sure all the pr's should have gssoc-ext label and level label then only your contributors will get points , also please be active and assign issues and merge the pr's
