### ISSUE TITLE
Adding smooth Scrolling effect

### ISSUE THREAD

**Issue by Hh440** [Aryainguz/picwise.co#39]
### Description
We need to implement a smooth scrolling effect across the PicWise website to enhance user experience and navigation. Currently, the scrolling behavior is default and abrupt, which detracts from the overall flow of the interface

### Features
- Seamless scrolling between website sections for a fluid user experience.
- Consistent scrolling behavior across all major browsers.
- Optimized for smooth performance on both mobile and desktop devices.
- Lightweight implementation to maintain website speed and performance.
- Customizable scroll speed for a balanced, natural feel.
- Non-intrusive scrolling that works well with fixed headers and other UI elements.

**Comment by Aryainguz** [comment]
please try adding some other features @Hh440
