### ISSUE TITLE
File Upload Glitch: Recurring Open Prompt 

### ISSUE THREAD

**Issue by antidude900** [Aryainguz/picwise.co#4]
Upon clicking the "Click to upload" section and selecting a file or canceling either by  "Cancel" button or the "Close" button, it unexpectedly brings the user back to the file selection window. The reopen happens once for a click on the  "Click to upload" section

https://github.com/user-attachments/assets/37598f85-be29-4e45-8879-2422c6c4ce1f

**Comment by Aryainguz** [comment]
go ahead on this @antidude900
