### ISSUE TITLE
adding code_of_conduct.md

### ISSUE THREAD

**Issue by jyothimanoj12** [Aryainguz/picwise.co#43]
A Code of Conduct ensures inclusivity, prevents harassment, clarifies behavioral expectations, encourages professionalism, and fosters a safe, welcoming community for contributors.

plz assisn me this issue under gsoc-extended , level 1 , hacktoberfest-accepted tag

**Comment by KiranBaliga** [comment]
This issue is already opened.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
And please add gssoc-ext label

**Comment by KiranBaliga** [comment]
@jyothimanoj12 @AnujSaha0111 Sorry, I am not the owner of this repo. This is a duplicate request. I have already requested the issue 3 days ago.
