### ISSUE TITLE
Implement "Move to Top" Button

### ISSUE THREAD

**Issue by myselfshivams** [Aryainguz/picwise.co#5]
Add a "Move to Top" button that becomes visible when users scroll down a certain distance on the page. This button should smoothly scroll the user back to the top of the page when clicked.

@Aryainguz  Please assign this task to me (myselfshivams) labels gssoc, hackoberfest.

**Comment by Ibrangrd** [comment]
I will do this work .

**Comment by Aryainguz** [comment]
go ahead @myselfshivams
