### ISSUE TITLE
Add Missing Favicon and Update Mobile Hamburger Menu to 'X' When Clicked

### ISSUE THREAD

**Issue by myselfshivams** [Aryainguz/picwise.co#6]
- Favicon Missing: The website currently have default vercel favicon. Add a favicon that appears on the browser tab.

- Mobile Hamburger Menu: On mobile devices, when the hamburger menu is clicked, it should change to an 'X' to indicate that the menu is open.

@Aryainguz Please assign this task to me(myselfshivams) labels gssoc, hackoberfest.

**Comment by Aryainguz** [comment]
go ahead on this @myselfshivams
