### ISSUE TITLE
File Upload Dialog Opens Twice on Image Click

### ISSUE THREAD

**Issue by Ahsankhalid618** [Aryainguz/picwise.co#62]
When clicking on the image to upload, the file upload dialog opens twice, leading to a confusing user experience.

![Screenshot 2024-10-12 164312](https://github.com/user-attachments/assets/ca2f1e42-81ba-421b-8603-c6a7ea5e0085)
![Screenshot 2024-10-12 164346](https://github.com/user-attachments/assets/a60f5cec-6230-491c-9b31-8f2eb4a49b9c)

**Steps to Reproduce:**

1. Navigate to the upload section of the application.
2. Click on the image intended for upload.
3. Observe that the file upload dialog appears two times.

**Expected Behavior:** The file upload dialog should open only once when the image is clicked.

**Actual Behavior:** The file upload dialog opens twice, which can be confusing for users.

Assign me this issue with these labels, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

**Comment by Aryainguz** [comment]
Hey @Ahsankhalid618 please go ahead and fix this also please share a screen recoding video when submitting the PR

**Comment by Ahsankhalid618** [comment]
Got it. I am already working on it.

**Comment by Ahsankhalid618** [comment]
Fixed!

Removed duplicated behavior and optimized both desktop and mobile behavior for compression file upload.


https://github.com/user-attachments/assets/215fc697-1b7a-438c-b409-ce023a8e7349

Should I raise the PR ?
Kindly before merging the PR, add these labels, hacktoberfest, hacktoberfest-accepted, gssoc-ext, and level3. ❤️

**Comment by Aryainguz** [comment]
yes please go ahead @Ahsankhalid618
