### ISSUE TITLE
Improve Metadata and SEO for Picwise

### ISSUE THREAD

**Issue by myselfshivams** [Aryainguz/picwise.co#7]
The metadata is missing several important tags that can improve SEO and the appearance of shared links on social media:

- keywords: A tag to help improve SEO with relevant search terms.
- Additional Open Graph Tags: Including og:type, og:url, and og:site_name.
- Twitter Meta Tags: Adding twitter:card, twitter:title, twitter:description, and twitter:image for better link previews on Twitter.

@Aryainguz Please assign this to me (myselfshivams) labels gssoc, hackoberfest.

**Comment by Aryainguz** [comment]
Hey @myselfshivams let me know if you’re still on this or not

**Comment by myselfshivams** [comment]
> Hey @myselfshivams please let me know if you’re still on this or not

Hey @Aryainguz, yes, I’m still on it!...sorry for the delay I will create PR today only

**Comment by Aryainguz** [comment]
Cool

**Comment by myselfshivams** [comment]
> Cool

Hey @Aryainguz ,  Could you please add level 2 or 3 label.
