### ISSUE TITLE
Typo in Hero Section Title ("wihout" should be "without")

### ISSUE THREAD

**Issue by mohit-2003** [Aryainguz/picwise.co#9]
In the hero section of the website, the title contains a typo. The word "wihout" should be corrected to "without" in the sentence: "Compress image size upto 90% without losing much of pixels."
Please update the typo for accurate presentation.

![image](https://github.com/user-attachments/assets/a9fc5f34-f0aa-43ee-8803-50a68156dfab)

**Comment by mohit-2003** [comment]
I would like to contribute by fixing this issue as part of my GSSoC 2024 Extd participation. Kindly let me know the process for making this contribution.

**Comment by Aryainguz** [comment]
go ahead on this @mohit-2003
